### ISSUE TITLE
F-Droid Inclusion?

### ISSUE THREAD

**Issue by TPS** [CraZyLegenD/CoronaTracker#2]
@CraZyLegenD Would you be interested in having your app [packaged](https://gitlab.com/fdroid/rfp/issues/1315) for [F-Droid](https://f-droid.org/)?

@Poussinou Thanks for the 🎩tip.

@IzzySoft As always 🙇🏾‍♂️, I'd appreciate if you'd take a look for any blockers, beyond the obvious `NonFree`*, due to use of https://www.worldometers.info/coronavirus/

**Comment by IzzySoft** [comment]
On a quick glance, I cannot see any trackers. But I can see another potential issue (not only related to F-Droid but a general technical one): `versionName "1.0.3"` suggests this is not the first release (the releases tab confirms), but `versionCode 1` means there never have been any updates. @CraZyLegenD please remember to always increase `versionCode` whenever releasing a new version, as that's what Android uses to tell them apart. If that's not changed, Android won't accept it as "update" as it considers it to be the very same version. Besides that, the releases tab shows a 1.0.4 while `build.gradle` still says 1.0.3?

**Comment by CraZyLegenD** [comment]
> On a quick glance, I cannot see any trackers. But I can see another potential issue (not only related to F-Droid but a general technical one): `versionName "1.0.3"` suggests this is not the first release (the releases tab confirms), but `versionCode 1` means there never have been any updates. @CraZyLegenD please remember to always increase `versionCode` whenever releasing a new version, as that's what Android uses to tell them apart. If that's not changed, Android won't accept it as "update" as it considers it to be the very same version. Besides that, the releases tab shows a 1.0.4 while `build.gradle` still says 1.0.3?

I never really planned on rolling the updates on F-droid, I know these things as they're the same rules as on Google play, but I'll change everything to match and be up to date everywhere if such case, no problems

**Comment by TPS** [comment]
@CraZyLegenD Would you mind if F-droid packaged it, anyway?

Also, I understand that [Google isn't allowing many COVID-19–related apps](https://www.forbes.com/sites/thomasbrewster/2020/03/24/google-bans-coronavirus-apps-but-after-400000-downloads/), so getting distribution for your work might be tough.

**Comment by CraZyLegenD** [comment]
> @CraZyLegenD Would you mind if F-droid packaged it, anyway?
> 
> Also, I understand that [Google isn't allowing many COVID-19–related apps](https://www.forbes.com/sites/thomasbrewster/2020/03/24/google-bans-coronavirus-apps-but-after-400000-downloads/), so getting distribution for your work might be tough.

I don't mind it being distributed on F-droid, I myself am using F-droid and understand about the COVID-19 apps that Google play restricts, this app was never meant to be distributed, it was built for personal usage, but as I can see it caught attention to other people so I don't really mind it being used by others

@IzzySoft I've fixed the versioning in this [commit](https://github.com/CraZyLegenD/CoronaTracker/commit/20156a8fb27e829f016388a4432f33afd3a32d49), everything is in sync.

**Comment by TPS** [comment]
RFP lives @ https://gitlab.com/fdroid/rfp/issues/1315

**Comment by TPS** [comment]
@CraZyLegenD I don't know if you're following along, but the F-Droid🤖 had a [security note re: your Gradle config](https://gitlab.com/fdroid/rfp/issues/1315#note_327265630).

**Comment by CraZyLegenD** [comment]
> @CraZyLegenD I don't know if you're following along, but the F-Droid had a [security note re: your Gradle config](https://gitlab.com/fdroid/rfp/issues/1315#note_327265630).

I'm busy with other things, saw what izzy commented but I don't have time for that now, if someone can make a pull request i'll appreciate it

**Comment by CraZyLegenD** [comment]
@TPS  @IzzySoft  I've updated the gradle SHA sum, is that everything ?

**Comment by IzzySoft** [comment]
Fastlane was the crucial point. I've added the metadata now and kicked it "upstairs" for our packagers to check.

**Comment by CraZyLegenD** [comment]
> Fastlane was the crucial point. I've added the metadata now and kicked it "upstairs" for our packagers to check.

Just woke up and saw, how do the updates happen on F-droid, do I just push a github release and update fastlane and f-droid knows?

**Comment by IzzySoft** [comment]
Basically yes – as long as you didn't forget to increase `versionCode`, kept the tag name pattern, and have it match what it matched before (usually `versionName`). The bot scans periodically for updates (multiple times a week), but it might take several days (sometimes more than a week) for new versions to show up; for one, our current build server is a bit "shaky" (we're working on a new set of build servers currently to alleviate that), and for the other, there's some manual work involved each time (at least signing).
